apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-infra
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: infra
    server: https://kubernetes.default.svc
  source:
    path: infra
    repoURL: https://github.com/aniketuniverse/self-service-azure.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
