apiVersion: v1
kind: Secret
metadata:
  name: azure-creds
  namespace: crossplane-system
type: Opaque
data:
  clientId: <clientId>
  clientSecret: clientSecret
  tenantId: tenantId
  subscriptionId: subscriptionId